#include <bits/stdc++.h>    //std::stoi, size_t

class BaseClass{
    private:

    public:

        BaseClass(){}
        ~BaseClass(){};
};

int main(){
    //Init values / open file
    std::string filename = "7/input2.txt";
    std::ifstream file_stream(filename,std::ios::in);
    std::string line; 

    //Parse file
    while(file_stream){
        getline(file_stream,line);
        if(line.empty() || line[0] == '\n'){
            continue;
        }
    }

    std::cout << "The answer for this day is " << answer << " (part1).\n";
    return 0;
}

//launch.json
// {"configurations": [{
//     "name": "(gdb) Launch",
//     "type": "cppdbg",
//     "request": "launch",
//     "program": "${workspaceFolder}/${fileBasenameNoExtension}.elf",
//     "stopAtEntry": false,
//     "cwd" : "${workspaceFolder}",
//     "externalConsole":false,
//     "MIMode": "gdb",
//     "miDebuggerPath": "/usr/bin/gdb",
//     "setupCommands":[{
//         "description":"Enable pretty-printing for gdb",
//         "text":"--enable-pretty-printing",
//         "ignoreFailures" : true
//     }],
//     "preLaunchTask": "build"
// }]}
  
//tasks.json
// {
//     "version": "2.0.0",
//     "tasks": [
//         {
//             "label": "build",
//             "type": "shell",
//             "command": "/usr/bin/g++",
//             "group": "build",
//             "args": [
//                 "-g3",
//                 "-Wall",
//                 "-Werror",
//                 "-fno-omit-frame-pointer",
//                 "-Wno-format-security",
//                 "${fileBasenameNoExtension}/${fileBasename}",
//                 "-o",
//                 "${workspaceFolder}/${fileBasenameNoExtension}.elf",
//                 "&&",
//                 "chmod",
//                 "+x",
//                 "${workspaceFolder}/${fileBasenameNoExtension}.elf"
//             ]
//         },
//         {
//             "type": "cppbuild",
//             "label": "C/C++: g++ build active file",
//             "command": "/usr/bin/g++",
//             "args": [
//                 "-fdiagnostics-color=always",
//                 "-g",
//                 "${file}",
//                 "-o",
//                 "${fileDirname}/${fileBasenameNoExtension}"
//             ],
//             "options": {
//                 "cwd": "${fileDirname}"
//             },
//             "problemMatcher": [
//                 "$gcc"
//             ],
//             "group": {
//                 "kind": "build",
//                 "isDefault": true
//             },
//             "detail": "Task generated by Debugger."
//         }
//     ]
// }
